name: "Publish"
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: self-hosted
    if: ${{ !github.event.fork && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - name: 🚀 Release
        uses: tradeshift/actions-semantic-release@v1
        id: semantic-release
        with:
          registry: https://npm.pkg.github.com/
          npm_publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
