name: "Test Tag"

on:
  push:
    tags:
      - v0*
      - v1*
      - v2*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test Tag
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [Push]
        with:
          fetch-depth: 0

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        run: npm ci

      - name: Compile
        run: npm run build

      - name: Test tag Workflow
        uses: ./
        with:
          main-branch-name: ${{ github.ref_name }}
          use-tag: true
